language: python

python:
  - "3.4"

matrix:
  include:
  # works on Precise and Trusty
  - os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-4.9
    env:
      - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

before_install:
  - eval "${MATRIX_EVAL}"

install:
  - pip install numpy
  - CC=g++-4.9 CXX=g++-4.9 python setup.py build_ext -DDEBUG -DBSF_AND install

script:
  - python tutorial/test_bsf.py

notifications:
  email: false
